sudo: required
services:
  - docker

before_install:
  - docker build -t krse22/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true krse22/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-129262059706"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"